# Generated by Django 2.1rc1 on 2018-08-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codekvng', '0002_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
